import { CategoryType } from "@/types/all";


export const categories: CategoryType[] = [
    {
        id: 'produce',
        name: 'Produce',
        slug: 'produce',
        color: '#10B981',
        icon: 'Apple',
        description: 'Fresh fruits and vegetables',
        type: 'system',
        itemCount: 0,
        frequency: 'weekly',
        lastUsed: '',
        recentItems: [],
        isActive: true,
        usagePercentage: 0,
        createdBy: null,
        createdAt: '2025-01-01T00:00:00Z',
        updatedAt: '2025-01-01T00:00:00Z',
        meta: { emoji: '🍎' }
    },
    {
        id: 'dairy',
        name: 'Dairy & Eggs',
        slug: 'dairy-eggs',
        color: '#3B82F6',
        icon: 'Milk',
        description: 'Milk, cheese, yogurt, and eggs',
        type: 'system',
        itemCount: 0,
        frequency: 'weekly',
        lastUsed: '',
        recentItems: [],
        isActive: true,
        usagePercentage: 0,
        createdBy: null,
        createdAt: '2025-01-01T00:00:00Z',
        updatedAt: '2025-01-01T00:00:00Z',
        meta: { emoji: '🥛' }
    },
    {
        id: 'meat',
        name: 'Meat & Seafood',
        slug: 'meat-seafood',
        color: '#EF4444',
        icon: 'Fish',
        description: 'Fresh meat and seafood',
        type: 'system',
        itemCount: 0,
        frequency: 'weekly',
        lastUsed: '',
        recentItems: [],
        isActive: true,
        usagePercentage: 0,
        createdBy: null,
        createdAt: '2025-01-01T00:00:00Z',
        updatedAt: '2025-01-01T00:00:00Z',
        meta: { emoji: '🍖' }
    },
    {
        id: 'pantry',
        name: 'Pantry',
        slug: 'pantry',
        color: '#F59E0B',
        icon: 'Package',
        description: 'Dry goods and shelf-stable items',
        type: 'system',
        itemCount: 0,
        frequency: 'biweekly',
        lastUsed: '',
        recentItems: [],
        isActive: true,
        usagePercentage: 0,
        createdBy: null,
        createdAt: '2025-01-01T00:00:00Z',
        updatedAt: '2025-01-01T00:00:00Z',
        meta: { emoji: '📦' }
    },
    {
        id: 'frozen',
        name: 'Frozen',
        slug: 'frozen',
        color: '#06B6D4',
        icon: 'Snowflake',
        description: 'Frozen foods and desserts',
        type: 'system',
        itemCount: 0,
        frequency: 'monthly',
        lastUsed: '',
        recentItems: [],
        isActive: true,
        usagePercentage: 0,
        createdBy: null,
        createdAt: '2025-01-01T00:00:00Z',
        updatedAt: '2025-01-01T00:00:00Z',
        meta: { emoji: '❄️' }
    },
    {
        id: 'household',
        name: 'Household',
        slug: 'household',
        color: '#8B5CF6',
        icon: 'Home',
        description: 'Cleaning and home supplies',
        type: 'system',
        itemCount: 0,
        frequency: 'monthly',
        lastUsed: '',
        recentItems: [],
        isActive: true,
        usagePercentage: 0,
        createdBy: null,
        createdAt: '2025-01-01T00:00:00Z',
        updatedAt: '2025-01-01T00:00:00Z',
        meta: { emoji: '🏡' }
    }
];
